server.port: 8888
spring.application.name: config-server

spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

wavefront.application.name: microservice-workshop
wavefront.application.service: ${spring.application.name}
management.metrics.export.wavefront.api-token: ${WAVEFRONT_TOKEN}
management.metrics.export.wavefront.uri: https://wavefront.surF
---
spring.profiles: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo
