apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: microservice-demo/product-service:v1
#          image: microservice-demo/product-service:v2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,prod"
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "400Mi"
